# Generated by Django 2.0 on 2017-12-12 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20171212_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='mongoid',
            field=models.TextField(default='zFUQMDwuDJyMRJT6', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
