# Generated by Django 2.0 on 2017-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20171212_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='mongoid',
            field=models.TextField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
