# Generated by Django 2.0 on 2017-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0006_auto_20171212_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='mongoid',
            field=models.TextField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
